name: dart_custom_dump_test
description: Test utilities for dart_custom_dump package
version: 0.1.0
repository: https://github.com/tisohjung/tca_flutter/tree/main/packages/dart_custom_dump_test
issue_tracker: https://github.com/tisohjung/tca_flutter/issues
homepage: https://github.com/tisohjung/tca_flutter
topics: [dump, diffing, debugging]

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  test: ^1.24.0
  dart_custom_dump: ^0.0.1

dev_dependencies:
  lints: ^3.0.0 
  coverage: ^1.8.0