name: dart_custom_dump
description: A collection of tools for debugging, diffing, and testing your application's data structures.
version: 0.0.1
repository: https://github.com/tisohjung/tca_flutter/tree/main/packages/dart_custom_dump
issue_tracker: https://github.com/tisohjung/tca_flutter/issues
homepage: https://github.com/tisohjung/tca_flutter
topics: [dump, diffing, debugging]

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  meta: ^1.10.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  coverage: ^1.8.0
